[package]
name = "wave-simulator"
version = "0.1.0"
authors = ["Lonsdaleiter <lonsdaleiteproductions@gmail.com>"]
edition = "2018"

[dependencies]
cull-canyon = { path = "../cull-canyon" }
winit = "0.22.1"
png = "0.16.3"
cgmath = "0.17.0"
objc = "0.2.7"
